import 'package:avrai/core/models/spots/spot.dart';

import 'trigger_decision.dart' show ListEngagementMetrics;

/// Suggested List Model
///
/// Represents an AI-generated list suggestion with places, scores, and metadata.
/// This is the output of the Perpetual List Orchestrator.
///
/// Part of Phase 1: Core Models for Perpetual List Orchestrator

/// A suggested list generated by the AI
class SuggestedList {
  /// Unique identifier for this suggestion
  final String id;

  /// Title of the list
  final String title;

  /// Description of why this list was suggested
  final String description;

  /// Places included in this list
  final List<Spot> places;

  /// Theme/category of the list
  final String theme;

  /// When this list was generated
  final DateTime generatedAt;

  /// Average compatibility score across all places (0.0 to 1.0)
  final double avgCompatibilityScore;

  /// Novelty score (how new/fresh this suggestion is)
  final double noveltyScore;

  /// Timeliness score (how appropriate for current time/context)
  final double timelinessScore;

  /// Trigger reasons that led to this list
  final List<String> triggerReasons;

  /// Whether this list is pinned (won't expire)
  final bool isPinned;

  /// Additional metadata
  final Map<String, dynamic> metadata;

  const SuggestedList({
    required this.id,
    required this.title,
    required this.description,
    required this.places,
    required this.theme,
    required this.generatedAt,
    this.avgCompatibilityScore = 0.0,
    this.noveltyScore = 0.5,
    this.timelinessScore = 0.5,
    this.triggerReasons = const [],
    this.isPinned = false,
    this.metadata = const {},
  });
  
  /// Create a copy with updated pinned state
  SuggestedList copyWithPinned(bool pinned) {
    return SuggestedList(
      id: id,
      title: title,
      description: description,
      places: places,
      theme: theme,
      generatedAt: generatedAt,
      avgCompatibilityScore: avgCompatibilityScore,
      noveltyScore: noveltyScore,
      timelinessScore: timelinessScore,
      triggerReasons: triggerReasons,
      isPinned: pinned,
      metadata: metadata,
    );
  }

  /// Number of places in the list
  int get placeCount => places.length;

  /// Check if list is empty
  bool get isEmpty => places.isEmpty;

  /// Check if list is non-empty
  bool get isNotEmpty => places.isNotEmpty;

  /// Get place IDs
  List<String> get placeIds => places.map((p) => p.id).toList();

  /// Overall quality score (combination of all scores)
  double get qualityScore {
    return (avgCompatibilityScore * 0.5 +
            noveltyScore * 0.25 +
            timelinessScore * 0.25)
        .clamp(0.0, 1.0);
  }

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'description': description,
      'places': places.map((p) => p.toJson()).toList(),
      'theme': theme,
      'generatedAt': generatedAt.toIso8601String(),
      'avgCompatibilityScore': avgCompatibilityScore,
      'noveltyScore': noveltyScore,
      'timelinessScore': timelinessScore,
      'triggerReasons': triggerReasons,
      'metadata': metadata,
    };
  }

  /// Create a copy with updated fields
  SuggestedList copyWith({
    String? id,
    String? title,
    String? description,
    List<Spot>? places,
    String? theme,
    DateTime? generatedAt,
    double? avgCompatibilityScore,
    double? noveltyScore,
    double? timelinessScore,
    List<String>? triggerReasons,
    Map<String, dynamic>? metadata,
  }) {
    return SuggestedList(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      places: places ?? this.places,
      theme: theme ?? this.theme,
      generatedAt: generatedAt ?? this.generatedAt,
      avgCompatibilityScore: avgCompatibilityScore ?? this.avgCompatibilityScore,
      noveltyScore: noveltyScore ?? this.noveltyScore,
      timelinessScore: timelinessScore ?? this.timelinessScore,
      triggerReasons: triggerReasons ?? this.triggerReasons,
      metadata: metadata ?? this.metadata,
    );
  }

  @override
  String toString() {
    return 'SuggestedList($title: $placeCount places, '
        'quality: ${(qualityScore * 100).toStringAsFixed(0)}%)';
  }
}

/// A scored candidate for inclusion in a list
class ScoredCandidate {
  /// The list candidate
  final ListCandidate candidate;

  /// Score from string theory possibility matching
  final double possibilityScore;

  /// Novelty score (0.0 = very familiar, 1.0 = completely new)
  final double noveltyScore;

  /// Timeliness score (0.0 = bad time, 1.0 = perfect time)
  final double timelinessScore;

  /// Combined score
  final double combinedScore;

  const ScoredCandidate({
    required this.candidate,
    required this.possibilityScore,
    required this.noveltyScore,
    required this.timelinessScore,
    required this.combinedScore,
  });

  /// Get the place
  Spot get place => candidate.place;

  /// Get the category
  String get category => candidate.category;
}

/// A candidate place for list inclusion
class ListCandidate {
  /// The place
  final Spot place;

  /// Quantum state representation (for matching)
  final dynamic quantumState;

  /// Category of the place
  final String category;

  const ListCandidate({
    required this.place,
    this.quantumState,
    required this.category,
  });
}

/// Types of list interactions
enum ListInteractionType {
  /// User viewed the list
  viewed,

  /// User saved/liked the list
  saved,

  /// User dismissed the list
  dismissed,

  /// User visited a place from the list
  placeVisited,

  /// User shared the list
  shared,

  /// User added list to their own collection
  addedToCollection,
}

/// Record of user interaction with a suggested list
class ListInteraction {
  /// Type of interaction
  final ListInteractionType type;

  /// The list that was interacted with
  final String listId;

  /// Places involved in the interaction (e.g., which place was visited)
  final List<Spot> involvedPlaces;

  /// When the interaction occurred
  final DateTime timestamp;

  /// Duration of interaction (e.g., how long they viewed)
  final Duration? duration;

  /// Additional metadata
  final Map<String, dynamic> metadata;

  const ListInteraction({
    required this.type,
    required this.listId,
    this.involvedPlaces = const [],
    required this.timestamp,
    this.duration,
    this.metadata = const {},
  });

  /// Check if this was a positive interaction
  bool get isPositive =>
      type == ListInteractionType.saved ||
      type == ListInteractionType.placeVisited ||
      type == ListInteractionType.shared ||
      type == ListInteractionType.addedToCollection;

  /// Check if this was a negative interaction
  bool get isNegative => type == ListInteractionType.dismissed;

  /// Check if this was a neutral interaction
  bool get isNeutral => type == ListInteractionType.viewed;

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    return {
      'type': type.name,
      'listId': listId,
      'involvedPlaces': involvedPlaces.map((p) => p.toJson()).toList(),
      'timestamp': timestamp.toIso8601String(),
      'durationMs': duration?.inMilliseconds,
      'metadata': metadata,
    };
  }

  /// Create from JSON
  factory ListInteraction.fromJson(Map<String, dynamic> json) {
    return ListInteraction(
      type: ListInteractionType.values.firstWhere(
        (t) => t.name == json['type'],
        orElse: () => ListInteractionType.viewed,
      ),
      listId: json['listId'] as String,
      involvedPlaces: (json['involvedPlaces'] as List?)
              ?.map((p) => Spot.fromJson(p as Map<String, dynamic>))
              .toList() ??
          [],
      timestamp: DateTime.parse(json['timestamp'] as String),
      duration: json['durationMs'] != null
          ? Duration(milliseconds: json['durationMs'] as int)
          : null,
      metadata: Map<String, dynamic>.from(json['metadata'] as Map? ?? {}),
    );
  }
}

/// History of list suggestions and interactions
class ListHistory {
  /// Recently suggested lists
  final List<SuggestedList> recentSuggestions;

  /// User-created lists
  final List<String> createdListIds;

  /// Lists the user liked/saved
  final List<String> likedListIds;

  /// Lists the user follows
  final List<String> followedListIds;

  /// Recent interactions
  final List<ListInteraction> recentInteractions;

  const ListHistory({
    this.recentSuggestions = const [],
    this.createdListIds = const [],
    this.likedListIds = const [],
    this.followedListIds = const [],
    this.recentInteractions = const [],
  });

  /// Check if a list was recently suggested
  bool wasRecentlySuggested(String listId) {
    return recentSuggestions.any((list) => list.id == listId);
  }

  /// Check if a place was recently suggested
  bool wasPlaceRecentlySuggested(String placeId) {
    for (final list in recentSuggestions) {
      if (list.placeIds.contains(placeId)) return true;
    }
    return false;
  }

  /// Calculate engagement metrics from recent interactions
  ListEngagementMetrics calculateEngagement() {
    if (recentInteractions.isEmpty) {
      return const ListEngagementMetrics();
    }

    int positive = 0;
    int dismissed = 0;
    int saved = 0;
    int placesVisited = 0;

    for (final interaction in recentInteractions) {
      if (interaction.isPositive) positive++;
      if (interaction.type == ListInteractionType.dismissed) dismissed++;
      if (interaction.type == ListInteractionType.saved) saved++;
      if (interaction.type == ListInteractionType.placeVisited) {
        placesVisited += interaction.involvedPlaces.length;
      }
    }

    return ListEngagementMetrics(
      totalSuggested: recentSuggestions.length,
      positiveInteractions: positive,
      dismissed: dismissed,
      saved: saved,
      placesVisited: placesVisited,
    );
  }

  /// Empty history for new users
  static const ListHistory empty = ListHistory();
}

// Note: ListEngagementMetrics is defined in trigger_decision.dart
// Import from there to use it
