import 'dart:developer' as developer;
import 'package:get_it/get_it.dart';
import 'package:avrai/core/ai/action_models.dart';
import 'package:avrai/core/models/spots/spot.dart';
import 'package:avrai/core/models/misc/list.dart';
import 'package:avrai/core/services/misc/action_error_handler.dart';
import 'package:avrai/domain/usecases/spots/create_spot_usecase.dart';
import 'package:avrai/domain/usecases/lists/create_list_usecase.dart';
import 'package:avrai/domain/usecases/lists/update_list_usecase.dart';
import 'package:avrai/domain/repositories/spots_repository.dart';
import 'package:avrai/domain/repositories/lists_repository.dart';

/// Action Executor for Phase 5: Action Execution System
/// Executes action intents by calling appropriate use cases
class ActionExecutor {
  static const String _logName = 'ActionExecutor';

  final CreateSpotUseCase? _createSpotUseCase;
  final CreateListUseCase? _createListUseCase;
  final UpdateListUseCase? _updateListUseCase;
  final SpotsRepository? _spotsRepository;
  final ListsRepository? _listsRepository;

  ActionExecutor({
    CreateSpotUseCase? createSpotUseCase,
    CreateListUseCase? createListUseCase,
    UpdateListUseCase? updateListUseCase,
    SpotsRepository? spotsRepository,
    ListsRepository? listsRepository,
  })  : _createSpotUseCase = createSpotUseCase,
        _createListUseCase = createListUseCase,
        _updateListUseCase = updateListUseCase,
        _spotsRepository = spotsRepository,
        _listsRepository = listsRepository;

  /// Create ActionExecutor from DI container
  factory ActionExecutor.fromDI() {
    try {
      return ActionExecutor(
        createSpotUseCase: GetIt.instance<CreateSpotUseCase>(),
        createListUseCase: GetIt.instance<CreateListUseCase>(),
        updateListUseCase: GetIt.instance<UpdateListUseCase>(),
        spotsRepository: GetIt.instance<SpotsRepository>(),
        listsRepository: GetIt.instance<ListsRepository>(),
      );
    } catch (e) {
      developer.log('Error creating ActionExecutor from DI: $e',
          name: _logName);
      return ActionExecutor();
    }
  }

  /// Execute an action intent
  Future<ActionResult> execute(ActionIntent intent) async {
    try {
      developer.log('Executing action: ${intent.type}', name: _logName);

      if (intent is CreateSpotIntent) {
        return await executeCreateSpot(intent);
      } else if (intent is CreateListIntent) {
        return await executeCreateList(intent);
      } else if (intent is AddSpotToListIntent) {
        return await executeAddSpotToList(intent);
      } else {
        return ActionResult.failure(
          error: 'Unknown action type: ${intent.type}',
          intent: intent,
        );
      }
    } catch (e, stackTrace) {
      // Use ActionErrorHandler for consistent error logging
      ActionErrorHandler.logError(
        e,
        null,
        intent,
        context: 'ActionExecutor.execute',
      );
      developer.log('Stack trace: $stackTrace', name: _logName);
      return ActionResult.failure(
        error: 'Failed to execute action: $e',
        intent: intent,
      );
    }
  }

  /// Execute create spot intent
  Future<ActionResult> executeCreateSpot(CreateSpotIntent intent) async {
    try {
      if (_createSpotUseCase == null) {
        return ActionResult.failure(
          error: 'CreateSpotUseCase not available',
          intent: intent,
        );
      }

      final now = DateTime.now();
      final spot = Spot(
        id: '', // Will be generated by repository
        name: intent.name,
        description: intent.description,
        latitude: intent.latitude,
        longitude: intent.longitude,
        category: intent.category,
        rating: 0.0,
        createdBy: intent.userId,
        createdAt: now,
        updatedAt: now,
        address: intent.address,
        tags: intent.tags,
      );

      final createdSpot = await _createSpotUseCase.call(spot);

      return ActionResult.success(
        message: 'Successfully created spot "${createdSpot.name}"',
        data: {'spotId': createdSpot.id, 'spotName': createdSpot.name},
        intent: intent,
      );
    } catch (e) {
      // Use ActionErrorHandler for consistent error logging
      ActionErrorHandler.logError(e, null, intent,
          context: 'executeCreateSpot');
      return ActionResult.failure(
        error: 'Failed to create spot: $e',
        intent: intent,
      );
    }
  }

  /// Execute create list intent
  Future<ActionResult> executeCreateList(CreateListIntent intent) async {
    try {
      if (_createListUseCase == null) {
        return ActionResult.failure(
          error: 'CreateListUseCase not available',
          intent: intent,
        );
      }

      final now = DateTime.now();
      final list = SpotList(
        id: '', // Will be generated by repository
        title: intent.title,
        description: intent.description,
        spots: const [],
        createdAt: now,
        updatedAt: now,
        category: intent.category,
        isPublic: intent.isPublic,
        spotIds: const [],
        curatorId: intent.userId,
        tags: intent.tags,
      );

      final createdList = await _createListUseCase.call(list);

      return ActionResult.success(
        message: 'Successfully created list "${createdList.title}"',
        data: {'listId': createdList.id, 'listName': createdList.title},
        intent: intent,
      );
    } catch (e) {
      // Use ActionErrorHandler for consistent error logging
      ActionErrorHandler.logError(e, null, intent,
          context: 'executeCreateList');
      return ActionResult.failure(
        error: 'Failed to create list: $e',
        intent: intent,
      );
    }
  }

  /// Execute add spot to list intent
  Future<ActionResult> executeAddSpotToList(AddSpotToListIntent intent) async {
    try {
      if (_updateListUseCase == null || _listsRepository == null) {
        return ActionResult.failure(
          error: 'UpdateListUseCase or ListsRepository not available',
          intent: intent,
        );
      }

      // Resolve spot ID if we have a name
      String spotId = intent.spotId;
      if (intent.metadata.containsKey('spotName')) {
        final spotName = intent.metadata['spotName'] as String;
        final resolvedSpotId = await _resolveSpotId(spotName);
        if (resolvedSpotId != null) {
          spotId = resolvedSpotId;
        } else {
          return ActionResult.failure(
            error: 'Could not find spot: $spotName',
            intent: intent,
          );
        }
      }

      // Resolve list ID if we have a name
      String listId = intent.listId;
      if (intent.metadata.containsKey('listName')) {
        final listName = intent.metadata['listName'] as String;
        final resolvedListId = await _resolveListId(listName, intent.userId);
        if (resolvedListId != null) {
          listId = resolvedListId;
        } else {
          return ActionResult.failure(
            error: 'Could not find list: $listName',
            intent: intent,
          );
        }
      }

      // Get the list by searching all lists
      final allLists = await _listsRepository.getLists();
      final list = allLists.firstWhere(
        (l) => l.id == listId,
        orElse: () => throw Exception('List not found'),
      );

      // Check if spot is already in list
      if (list.spotIds.contains(spotId)) {
        return ActionResult.success(
          message: 'Spot is already in the list',
          data: {'spotId': spotId, 'listId': listId},
          intent: intent,
        );
      }

      // Add spot to list
      final updatedSpotIds = List<String>.from(list.spotIds)..add(spotId);
      final updatedList = list.copyWith(
        spotIds: updatedSpotIds,
        updatedAt: DateTime.now(),
      );

      await _updateListUseCase.call(updatedList);

      return ActionResult.success(
        message: 'Successfully added spot to list',
        data: {'spotId': spotId, 'listId': listId},
        intent: intent,
      );
    } catch (e) {
      // Use ActionErrorHandler for consistent error logging
      ActionErrorHandler.logError(e, null, intent,
          context: 'executeAddSpotToList');
      return ActionResult.failure(
        error: 'Failed to add spot to list: $e',
        intent: intent,
      );
    }
  }

  /// Resolve spot name to spot ID
  Future<String?> _resolveSpotId(String spotName) async {
    try {
      if (_spotsRepository == null) return null;

      // Try to find spot by name (this would need a search method)
      // For now, return null - this would need repository support
      // TODO: Add searchByName method to SpotsRepository
      return null;
    } catch (e) {
      developer.log('Error resolving spot ID: $e', name: _logName);
      return null;
    }
  }

  /// Resolve list name to list ID
  Future<String?> _resolveListId(String listName, String userId) async {
    try {
      if (_listsRepository == null) return null;

      // Get all lists and filter by user and name
      final allLists = await _listsRepository.getLists();
      for (final list in allLists) {
        // Check if list belongs to user (curatorId) and matches name
        if ((list.curatorId == userId || list.curatorId == null) &&
            list.title.toLowerCase() == listName.toLowerCase()) {
          return list.id;
        }
      }

      return null;
    } catch (e) {
      developer.log('Error resolving list ID: $e', name: _logName);
      return null;
    }
  }
}
