import 'package:avrai_core/contracts/air_gap_contract.dart';
import 'package:avrai_runtime_os/services/passive_collection/smart_passive_collection_service.dart';

/// Prepares raw physical [DwellEvent] data for safe extraction by the Air Gap.
/// 
/// Dwell Events (generated by the SmartPassiveCollectionService) contain raw GPS 
/// coordinates and precise timestamps. This violates the zero-knowledge privacy mandate 
/// if acted upon directly by the LLM. 
/// 
/// This adapter packages the raw data into a toxic [RawDataPayload] and passes it 
/// to the [AirGapContract] (TupleExtractionEngine), where it will be reverse-geocoded,
/// converted into abstract mathematical tuples (e.g. "User likes Jazz Bars"), 
/// and then permanently destroyed.
/// A concrete implementation of RawDataPayload for physical dwelling events.
class DwellEventPayload extends RawDataPayload {
  final String _content;

  DwellEventPayload({
    required String sourceId,
    required DateTime capturedAt,
    required String rawContent,
  })  : _content = rawContent,
        super(capturedAt: capturedAt, sourceId: sourceId);

  @override
  String get rawContent => _content;
}

class DwellEventIntakeAdapter {
  final AirGapContract _airGap;

  DwellEventIntakeAdapter(this._airGap);

  /// Takes a raw DwellEvent and flushes it through the Air Gap for safe extraction.
  Future<void> ingestDwellEvent(DwellEvent event) async {
    // 1. Serialize the raw physical reality into a string payload
    final rawContext = '''
DWELL_EVENT:
Start: ${event.startTime.toIso8601String()}
End: ${event.endTime.toIso8601String()}
Duration: ${event.endTime.difference(event.startTime).inMinutes} minutes
Latitude: ${event.latitude}
Longitude: ${event.longitude}
Encounters: ${event.encounteredAgentIds.join(', ')}
''';

    // 2. Package it as a toxic payload
    final payload = DwellEventPayload(
      sourceId: 'passive_dwell_sensor',
      rawContent: rawContext,
      capturedAt: DateTime.now(),
    );

    // 3. Throw it over the Air Gap
    // The Air Gap will run the local LLM/deterministic extractors to convert this 
    // into SemanticTuples (e.g. "Subject: user, Predicate: dwelled_at, Object: location_category_cafe")
    // and then destroy the payload string.
    await _airGap.scrubAndExtract(payload);
  }

  /// Ingests a batch of multiple DwellEvents (e.g. from the nightly batch process)
  Future<void> ingestBatch(List<DwellEvent> events) async {
    for (final event in events) {
      await ingestDwellEvent(event);
    }
  }
}
