import 'package:avrai_core/contracts/air_gap_contract.dart';
import 'package:avrai_core/models/air_gap/air_gap_compression_models.dart';
import 'package:avrai_core/schemas/semantic_tuple.dart';
import 'package:avrai_runtime_os/kernel/what/what_runtime_ingestion_service.dart';
import 'package:avrai_runtime_os/services/intake/air_gap_compression_runtime_service.dart';
import 'package:avrai_runtime_os/services/intake/upward_air_gap_service.dart';
import 'package:avrai_runtime_os/services/infrastructure/supabase_service.dart';
import 'package:avrai_runtime_os/services/passive_collection/passive_dwell_reality_learning_service.dart';
import 'package:avrai_runtime_os/services/reality_model/governed_upward_learning_intake_service.dart';
import 'package:avrai_runtime_os/services/passive_collection/smart_passive_collection_service.dart';
import 'package:avrai_runtime_os/services/passive_collection/visit_locality_follow_up_planner_service.dart';

/// Prepares raw physical [DwellEvent] data for safe extraction by the Air Gap.
///
/// Dwell Events (generated by the SmartPassiveCollectionService) contain raw GPS
/// coordinates and precise timestamps. This violates the zero-knowledge privacy mandate
/// if acted upon directly by the LLM.
///
/// This adapter packages the raw data into a toxic [RawDataPayload] and passes it
/// to the [AirGapContract] (TupleExtractionEngine), where it will be reverse-geocoded,
/// converted into abstract mathematical tuples (e.g. "User likes Jazz Bars"),
/// and then permanently destroyed.
/// A concrete implementation of RawDataPayload for physical dwelling events.
class DwellEventPayload extends RawDataPayload {
  final String _content;

  const DwellEventPayload({
    required super.sourceId,
    required super.capturedAt,
    required String rawContent,
  }) : _content = rawContent;

  @override
  String get rawContent => _content;
}

class DwellEventIntakeAdapter {
  final AirGapContract _airGap;
  final WhatRuntimeIngestionService? _whatIngestion;
  final PassiveDwellRealityLearningService? _realityLearningService;
  final RuntimeAirGapCompressionService _compressionService;
  final GovernedUpwardLearningIntakeService?
      _governedUpwardLearningIntakeService;
  final VisitLocalityFollowUpPromptPlannerService?
      _visitLocalityFollowUpPlannerService;
  final SupabaseService? _supabaseService;

  DwellEventIntakeAdapter(
    this._airGap, {
    WhatRuntimeIngestionService? whatIngestion,
    PassiveDwellRealityLearningService? realityLearningService,
    GovernedUpwardLearningIntakeService? governedUpwardLearningIntakeService,
    VisitLocalityFollowUpPromptPlannerService?
        visitLocalityFollowUpPlannerService,
    SupabaseService? supabaseService,
    RuntimeAirGapCompressionService compressionService =
        const RuntimeAirGapCompressionService(),
  })  : _whatIngestion = whatIngestion,
        _realityLearningService = realityLearningService,
        _governedUpwardLearningIntakeService =
            governedUpwardLearningIntakeService,
        _visitLocalityFollowUpPlannerService =
            visitLocalityFollowUpPlannerService,
        _supabaseService = supabaseService,
        _compressionService = compressionService;

  /// Takes a raw DwellEvent and flushes it through the Air Gap for safe extraction.
  Future<List<SemanticTuple>> ingestDwellEvent(
    DwellEvent event, {
    String? ownerUserId,
  }) async {
    final projection = PassiveDwellLearningProjection.fromEvent(event);

    // 1. Serialize the raw physical reality into a string payload
    final rawContext = '''
DWELL_EVENT:
Start: ${event.startTime.toIso8601String()}
End: ${event.endTime.toIso8601String()}
Duration: ${event.endTime.difference(event.startTime).inMinutes} minutes
Latitude: ${event.latitude}
Longitude: ${event.longitude}
Encounters: ${event.encounteredAgentIds.join(', ')}
''';

    // 2. Package it as a toxic payload
    final payload = DwellEventPayload(
      sourceId: 'passive_dwell_sensor',
      rawContent: rawContext,
      capturedAt: DateTime.now(),
    );

    // 3. Throw it over the Air Gap
    // The Air Gap will run the local LLM/deterministic extractors to convert this
    // into SemanticTuples (e.g. "Subject: user, Predicate: dwelled_at, Object: location_category_cafe")
    // and then destroy the payload string.
    final tuples = await _airGap.scrubAndExtract(payload);
    final compressionBundle = _compressionService.compressSemanticTuples(
      contractId:
          'dwell_${event.startTime.microsecondsSinceEpoch}_${event.endTime.microsecondsSinceEpoch}',
      tuples: tuples,
      environmentId: _compressionService.buildEnvironmentId(
        surface: 'passive_dwell',
        localityCode: projection.localityStableKey,
      ),
      primaryLayer: AirGapKnowledgeLayer.personal,
      privacyLadderTag: 'amber',
      provenanceRefs: tuples.map((tuple) => tuple.id).toList(growable: false),
      metadata: <String, dynamic>{
        'localityStableKey': projection.localityStableKey,
        'durationMinutes': event.endTime.difference(event.startTime).inMinutes,
        'encounteredAgentCount': event.encounteredAgentIds.toSet().length,
      },
    );
    if (_whatIngestion != null) {
      final agentId = await _whatIngestion.currentAgentId();
      await _whatIngestion.ingestPassiveDwellObservation(
        entityRef: DefaultWhatRuntimeIngestionService.deterministicEntityRef(
          'passive_dwell',
          <String, Object?>{
            'lat': event.latitude.toStringAsFixed(4),
            'lon': event.longitude.toStringAsFixed(4),
          },
        ),
        observedAtUtc: event.endTime,
        agentId: agentId,
        semanticTuples: tuples,
        locationContext: <String, dynamic>{
          'latitude': event.latitude,
          'longitude': event.longitude,
          'localityStableKey': projection.localityStableKey,
        },
        temporalContext: <String, dynamic>{
          'startTime': event.startTime.toIso8601String(),
          'endTime': event.endTime.toIso8601String(),
          'durationMinutes':
              event.endTime.difference(event.startTime).inMinutes,
        },
        activityContext: 'lingering',
        structuredSignals: <String, dynamic>{
          'dwellDurationMinutes':
              event.endTime.difference(event.startTime).inMinutes,
          'encounteredAgentCount': event.encounteredAgentIds.toSet().length,
          'localityStableKey': projection.localityStableKey,
          'airGapCompression': compressionBundle.toStructuredSignals(),
        },
        confidence: 0.59,
        lineageRef:
            'dwell:${event.startTime.microsecondsSinceEpoch}:${event.endTime.microsecondsSinceEpoch}',
      );
      await _realityLearningService?.applyProjection(
        event: event,
        projection: projection,
        personalAgentId: agentId,
      );
    } else {
      await _realityLearningService?.applyProjection(
        event: event,
        projection: projection,
      );
    }
    await _stageLocalityObservationBestEffort(
      ownerUserId: ownerUserId,
      event: event,
      projection: projection,
    );
    return tuples;
  }

  /// Ingests a batch of multiple DwellEvents (e.g. from the nightly batch process)
  Future<void> ingestBatch(
    List<DwellEvent> events, {
    String? ownerUserId,
  }) async {
    for (final event in events) {
      await ingestDwellEvent(event, ownerUserId: ownerUserId);
    }
  }

  Future<void> _stageLocalityObservationBestEffort({
    required String? ownerUserId,
    required DwellEvent event,
    required PassiveDwellLearningProjection projection,
  }) async {
    final service = _governedUpwardLearningIntakeService;
    final resolvedOwnerUserId = ownerUserId?.trim().isNotEmpty == true
        ? ownerUserId!.trim()
        : _supabaseService?.currentUser?.id.trim();
    if (resolvedOwnerUserId == null || resolvedOwnerUserId.isEmpty) {
      return;
    }
    try {
      final occurredAtUtc = event.endTime.toUtc();
      if (service != null) {
        final airGapArtifact = const UpwardAirGapService().issueArtifact(
          originPlane: 'personal_device',
          sourceKind: 'locality_observation_intake',
          sourceScope: 'personal_agent',
          destinationCeiling: 'reality_model_agent',
          issuedAtUtc: DateTime.now().toUtc(),
          sanitizedPayload: <String, dynamic>{
            'sourceKind': 'locality_observation_intake',
            'sensorSource': 'passive_dwell',
            'localityStableKey': projection.localityStableKey,
            'durationMinutes':
                event.endTime.difference(event.startTime).inMinutes,
            'encounteredAgentCount': event.encounteredAgentIds.toSet().length,
            if (projection.socialContext.trim().isNotEmpty)
              'socialContext': projection.socialContext.trim(),
          },
        );
        await service.stageLocalityObservationIntake(
          ownerUserId: resolvedOwnerUserId,
          occurredAtUtc: occurredAtUtc,
          airGapArtifact: airGapArtifact,
          sourceKind: 'passive_dwell',
          localityStableKey: projection.localityStableKey,
          structuredSignals: projection.structuredSignals,
          locationContext: <String, dynamic>{
            'latitude': event.latitude,
            'longitude': event.longitude,
            'localityStableKey': projection.localityStableKey,
          },
          temporalContext: <String, dynamic>{
            'startTime': event.startTime.toUtc().toIso8601String(),
            'endTime': event.endTime.toUtc().toIso8601String(),
            'durationMinutes':
                event.endTime.difference(event.startTime).inMinutes,
          },
          socialContext: projection.socialContext,
          activityContext: 'passive_dwell',
          lineageRef:
              'dwell:${event.startTime.microsecondsSinceEpoch}:${event.endTime.microsecondsSinceEpoch}',
        );
      }
      await _visitLocalityFollowUpPlannerService?.createLocalityPlan(
        ownerUserId: resolvedOwnerUserId,
        occurredAtUtc: occurredAtUtc,
        sourceKind: 'passive_dwell',
        localityStableKey: projection.localityStableKey,
        structuredSignals: projection.structuredSignals,
        locationContext: <String, dynamic>{
          'latitude': event.latitude,
          'longitude': event.longitude,
          'localityStableKey': projection.localityStableKey,
        },
        temporalContext: <String, dynamic>{
          'startTime': event.startTime.toUtc().toIso8601String(),
          'endTime': event.endTime.toUtc().toIso8601String(),
          'durationMinutes':
              event.endTime.difference(event.startTime).inMinutes,
        },
        socialContext: projection.socialContext,
        activityContext: 'passive_dwell',
      );
    } catch (_) {
      // Best-effort only. Passive dwell processing must not fail if upward staging is unavailable.
    }
  }
}
