import 'package:avrai_core/contracts/air_gap_contract.dart';
import 'package:avrai_core/schemas/semantic_tuple.dart';
import 'package:avrai_runtime_os/kernel/what/what_runtime_ingestion_service.dart';
import 'package:avrai_runtime_os/services/passive_collection/passive_dwell_reality_learning_service.dart';
import 'package:avrai_runtime_os/services/passive_collection/smart_passive_collection_service.dart';

/// Prepares raw physical [DwellEvent] data for safe extraction by the Air Gap.
///
/// Dwell Events (generated by the SmartPassiveCollectionService) contain raw GPS
/// coordinates and precise timestamps. This violates the zero-knowledge privacy mandate
/// if acted upon directly by the LLM.
///
/// This adapter packages the raw data into a toxic [RawDataPayload] and passes it
/// to the [AirGapContract] (TupleExtractionEngine), where it will be reverse-geocoded,
/// converted into abstract mathematical tuples (e.g. "User likes Jazz Bars"),
/// and then permanently destroyed.
/// A concrete implementation of RawDataPayload for physical dwelling events.
class DwellEventPayload extends RawDataPayload {
  final String _content;

  const DwellEventPayload({
    required super.sourceId,
    required super.capturedAt,
    required String rawContent,
  }) : _content = rawContent;

  @override
  String get rawContent => _content;
}

class DwellEventIntakeAdapter {
  final AirGapContract _airGap;
  final WhatRuntimeIngestionService? _whatIngestion;
  final PassiveDwellRealityLearningService? _realityLearningService;

  DwellEventIntakeAdapter(
    this._airGap, {
    WhatRuntimeIngestionService? whatIngestion,
    PassiveDwellRealityLearningService? realityLearningService,
  })  : _whatIngestion = whatIngestion,
        _realityLearningService = realityLearningService;

  /// Takes a raw DwellEvent and flushes it through the Air Gap for safe extraction.
  Future<List<SemanticTuple>> ingestDwellEvent(DwellEvent event) async {
    final projection = PassiveDwellLearningProjection.fromEvent(event);

    // 1. Serialize the raw physical reality into a string payload
    final rawContext = '''
DWELL_EVENT:
Start: ${event.startTime.toIso8601String()}
End: ${event.endTime.toIso8601String()}
Duration: ${event.endTime.difference(event.startTime).inMinutes} minutes
Latitude: ${event.latitude}
Longitude: ${event.longitude}
Encounters: ${event.encounteredAgentIds.join(', ')}
''';

    // 2. Package it as a toxic payload
    final payload = DwellEventPayload(
      sourceId: 'passive_dwell_sensor',
      rawContent: rawContext,
      capturedAt: DateTime.now(),
    );

    // 3. Throw it over the Air Gap
    // The Air Gap will run the local LLM/deterministic extractors to convert this
    // into SemanticTuples (e.g. "Subject: user, Predicate: dwelled_at, Object: location_category_cafe")
    // and then destroy the payload string.
    final tuples = await _airGap.scrubAndExtract(payload);
    if (_whatIngestion != null) {
      final agentId = await _whatIngestion.currentAgentId();
      await _whatIngestion.ingestPassiveDwellObservation(
        entityRef: DefaultWhatRuntimeIngestionService.deterministicEntityRef(
          'passive_dwell',
          <String, Object?>{
            'lat': event.latitude.toStringAsFixed(4),
            'lon': event.longitude.toStringAsFixed(4),
          },
        ),
        observedAtUtc: event.endTime,
        agentId: agentId,
        semanticTuples: tuples,
        locationContext: <String, dynamic>{
          'latitude': event.latitude,
          'longitude': event.longitude,
          'localityStableKey': projection.localityStableKey,
        },
        temporalContext: <String, dynamic>{
          'startTime': event.startTime.toIso8601String(),
          'endTime': event.endTime.toIso8601String(),
          'durationMinutes':
              event.endTime.difference(event.startTime).inMinutes,
        },
        activityContext: 'lingering',
        structuredSignals: <String, dynamic>{
          'dwellDurationMinutes':
              event.endTime.difference(event.startTime).inMinutes,
          'encounteredAgentCount': event.encounteredAgentIds.toSet().length,
          'localityStableKey': projection.localityStableKey,
        },
        confidence: 0.59,
        lineageRef:
            'dwell:${event.startTime.microsecondsSinceEpoch}:${event.endTime.microsecondsSinceEpoch}',
      );
      await _realityLearningService?.applyProjection(
        event: event,
        projection: projection,
        personalAgentId: agentId,
      );
    } else {
      await _realityLearningService?.applyProjection(
        event: event,
        projection: projection,
      );
    }
    return tuples;
  }

  /// Ingests a batch of multiple DwellEvents (e.g. from the nightly batch process)
  Future<void> ingestBatch(List<DwellEvent> events) async {
    for (final event in events) {
      await ingestDwellEvent(event);
    }
  }
}
