// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1102607442;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'knot_math',
        ioDirectory: '../../native/knot_math/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Float64List crateApiCalculateAlexanderPolynomial({
    required List<double> braidData,
  });

  Float64List crateApiCalculateBoltzmannDistribution({
    required List<double> energies,
    required double temperature,
  });

  BigInt crateApiCalculateCrossingNumberFromBraid({
    required List<double> braidData,
  });

  double crateApiCalculateEntropy({required List<double> probabilities});

  double crateApiCalculateFreeEnergy({
    required double energy,
    required double entropy,
    required double temperature,
  });

  Float64List crateApiCalculateJonesPolynomial({
    required List<double> braidData,
  });

  double crateApiCalculateKnotEnergyFromPoints({
    required List<double> knotPoints,
  });

  double crateApiCalculateKnotStabilityFromPoints({
    required List<double> knotPoints,
  });

  double crateApiCalculateTopologicalCompatibility({
    required List<double> braidDataA,
    required List<double> braidDataB,
  });

  int crateApiCalculateWritheFromBraid({required List<double> braidData});

  double crateApiEvaluatePolynomial({
    required List<double> coefficients,
    required double x,
  });

  KnotResult crateApiGenerateKnotFromBraid({required List<double> braidData});

  double crateApiPolynomialDistance({
    required List<double> coefficientsA,
    required List<double> coefficientsB,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Float64List crateApiCalculateAlexanderPolynomial({
    required List<double> braidData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateAlexanderPolynomialConstMeta,
        argValues: [braidData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateAlexanderPolynomialConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_alexander_polynomial",
        argNames: ["braidData"],
      );

  @override
  Float64List crateApiCalculateBoltzmannDistribution({
    required List<double> energies,
    required double temperature,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(energies, serializer);
          sse_encode_f_64(temperature, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateBoltzmannDistributionConstMeta,
        argValues: [energies, temperature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateBoltzmannDistributionConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_boltzmann_distribution",
        argNames: ["energies", "temperature"],
      );

  @override
  BigInt crateApiCalculateCrossingNumberFromBraid({
    required List<double> braidData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateCrossingNumberFromBraidConstMeta,
        argValues: [braidData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateCrossingNumberFromBraidConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_crossing_number_from_braid",
        argNames: ["braidData"],
      );

  @override
  double crateApiCalculateEntropy({required List<double> probabilities}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(probabilities, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateEntropyConstMeta,
        argValues: [probabilities],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateEntropyConstMeta => const TaskConstMeta(
    debugName: "calculate_entropy",
    argNames: ["probabilities"],
  );

  @override
  double crateApiCalculateFreeEnergy({
    required double energy,
    required double entropy,
    required double temperature,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(energy, serializer);
          sse_encode_f_64(entropy, serializer);
          sse_encode_f_64(temperature, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateFreeEnergyConstMeta,
        argValues: [energy, entropy, temperature],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateFreeEnergyConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_free_energy",
        argNames: ["energy", "entropy", "temperature"],
      );

  @override
  Float64List crateApiCalculateJonesPolynomial({
    required List<double> braidData,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_64_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateJonesPolynomialConstMeta,
        argValues: [braidData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateJonesPolynomialConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_jones_polynomial",
        argNames: ["braidData"],
      );

  @override
  double crateApiCalculateKnotEnergyFromPoints({
    required List<double> knotPoints,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(knotPoints, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateKnotEnergyFromPointsConstMeta,
        argValues: [knotPoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateKnotEnergyFromPointsConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_knot_energy_from_points",
        argNames: ["knotPoints"],
      );

  @override
  double crateApiCalculateKnotStabilityFromPoints({
    required List<double> knotPoints,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(knotPoints, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateKnotStabilityFromPointsConstMeta,
        argValues: [knotPoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateKnotStabilityFromPointsConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_knot_stability_from_points",
        argNames: ["knotPoints"],
      );

  @override
  double crateApiCalculateTopologicalCompatibility({
    required List<double> braidDataA,
    required List<double> braidDataB,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidDataA, serializer);
          sse_encode_list_prim_f_64_loose(braidDataB, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateTopologicalCompatibilityConstMeta,
        argValues: [braidDataA, braidDataB],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateTopologicalCompatibilityConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_topological_compatibility",
        argNames: ["braidDataA", "braidDataB"],
      );

  @override
  int crateApiCalculateWritheFromBraid({required List<double> braidData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCalculateWritheFromBraidConstMeta,
        argValues: [braidData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalculateWritheFromBraidConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_writhe_from_braid",
        argNames: ["braidData"],
      );

  @override
  double crateApiEvaluatePolynomial({
    required List<double> coefficients,
    required double x,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(coefficients, serializer);
          sse_encode_f_64(x, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEvaluatePolynomialConstMeta,
        argValues: [coefficients, x],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvaluatePolynomialConstMeta => const TaskConstMeta(
    debugName: "evaluate_polynomial",
    argNames: ["coefficients", "x"],
  );

  @override
  KnotResult crateApiGenerateKnotFromBraid({required List<double> braidData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(braidData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_knot_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateKnotFromBraidConstMeta,
        argValues: [braidData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateKnotFromBraidConstMeta =>
      const TaskConstMeta(
        debugName: "generate_knot_from_braid",
        argNames: ["braidData"],
      );

  @override
  double crateApiPolynomialDistance({
    required List<double> coefficientsA,
    required List<double> coefficientsB,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_f_64_loose(coefficientsA, serializer);
          sse_encode_list_prim_f_64_loose(coefficientsB, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPolynomialDistanceConstMeta,
        argValues: [coefficientsA, coefficientsB],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPolynomialDistanceConstMeta => const TaskConstMeta(
    debugName: "polynomial_distance",
    argNames: ["coefficientsA", "coefficientsB"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  KnotResult dco_decode_knot_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return KnotResult(
      knotData: dco_decode_list_prim_f_64_strict(arr[0]),
      jonesPolynomial: dco_decode_list_prim_f_64_strict(arr[1]),
      alexanderPolynomial: dco_decode_list_prim_f_64_strict(arr[2]),
      crossingNumber: dco_decode_usize(arr[3]),
      writhe: dco_decode_i_32(arr[4]),
      signature: dco_decode_i_32(arr[5]),
      unknottingNumber: dco_decode_opt_box_autoadd_usize(arr[6]),
      bridgeNumber: dco_decode_usize(arr[7]),
      braidIndex: dco_decode_usize(arr[8]),
      determinant: dco_decode_i_32(arr[9]),
      arfInvariant: dco_decode_opt_box_autoadd_i_32(arr[10]),
      hyperbolicVolume: dco_decode_opt_box_autoadd_f_64(arr[11]),
      homflyPolynomial: dco_decode_opt_list_prim_f_64_strict(arr[12]),
    );
  }

  @protected
  List<double> dco_decode_list_prim_f_64_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  Float64List? dco_decode_opt_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_f_64_strict(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  KnotResult sse_decode_knot_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_knotData = sse_decode_list_prim_f_64_strict(deserializer);
    var var_jonesPolynomial = sse_decode_list_prim_f_64_strict(deserializer);
    var var_alexanderPolynomial = sse_decode_list_prim_f_64_strict(
      deserializer,
    );
    var var_crossingNumber = sse_decode_usize(deserializer);
    var var_writhe = sse_decode_i_32(deserializer);
    var var_signature = sse_decode_i_32(deserializer);
    var var_unknottingNumber = sse_decode_opt_box_autoadd_usize(deserializer);
    var var_bridgeNumber = sse_decode_usize(deserializer);
    var var_braidIndex = sse_decode_usize(deserializer);
    var var_determinant = sse_decode_i_32(deserializer);
    var var_arfInvariant = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_hyperbolicVolume = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_homflyPolynomial = sse_decode_opt_list_prim_f_64_strict(
      deserializer,
    );
    return KnotResult(
      knotData: var_knotData,
      jonesPolynomial: var_jonesPolynomial,
      alexanderPolynomial: var_alexanderPolynomial,
      crossingNumber: var_crossingNumber,
      writhe: var_writhe,
      signature: var_signature,
      unknottingNumber: var_unknottingNumber,
      bridgeNumber: var_bridgeNumber,
      braidIndex: var_braidIndex,
      determinant: var_determinant,
      arfInvariant: var_arfInvariant,
      hyperbolicVolume: var_hyperbolicVolume,
      homflyPolynomial: var_homflyPolynomial,
    );
  }

  @protected
  List<double> sse_decode_list_prim_f_64_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Float64List? sse_decode_opt_list_prim_f_64_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_f_64_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_knot_result(KnotResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_64_strict(self.knotData, serializer);
    sse_encode_list_prim_f_64_strict(self.jonesPolynomial, serializer);
    sse_encode_list_prim_f_64_strict(self.alexanderPolynomial, serializer);
    sse_encode_usize(self.crossingNumber, serializer);
    sse_encode_i_32(self.writhe, serializer);
    sse_encode_i_32(self.signature, serializer);
    sse_encode_opt_box_autoadd_usize(self.unknottingNumber, serializer);
    sse_encode_usize(self.bridgeNumber, serializer);
    sse_encode_usize(self.braidIndex, serializer);
    sse_encode_i_32(self.determinant, serializer);
    sse_encode_opt_box_autoadd_i_32(self.arfInvariant, serializer);
    sse_encode_opt_box_autoadd_f_64(self.hyperbolicVolume, serializer);
    sse_encode_opt_list_prim_f_64_strict(self.homflyPolynomial, serializer);
  }

  @protected
  void sse_encode_list_prim_f_64_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(
      self is Float64List ? self : Float64List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_f_64_strict(
    Float64List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_f_64_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
