// import 'package:flutter/material.dart';

/// The core data structure for the Trojan Horse UX (Spike 6).
/// Contains exactly 4 highly curated items derived from the user's
/// offline physical encounters and learned archetypes.
class DailySerendipityDrop {
  final DateTime date;

  // The contextual explanation generated by the local LLM batch process
  // e.g., "Based on the patterns of people you connected with yesterday..."
  final String llmContextualInsight;

  // The curated items
  final DropEvent event;
  final DropSpot spot;
  final DropCommunity community;
  final DropClub club;

  // Optional Spike 2: Orthogonal Wildcard
  // High friction or out of routine suggestion that matches latent quantum vibe
  final DropWildcard? wildcard;

  // Optional Latent Community from Fabric
  final DropLatentCommunity? latentCommunity;

  DailySerendipityDrop({
    required this.date,
    required this.llmContextualInsight,
    required this.event,
    required this.spot,
    required this.community,
    required this.club,
    this.wildcard,
    this.latentCommunity,
  });
  Map<String, dynamic> toJson() {
    return {
      'date': date.toIso8601String(),
      'llmContextualInsight': llmContextualInsight,
      'event': event.toJson(),
      'spot': spot.toJson(),
      'community': community.toJson(),
      'club': club.toJson(),
      'wildcard': wildcard?.toJson(),
      'latentCommunity': latentCommunity?.toJson(),
    };
  }

  factory DailySerendipityDrop.fromJson(Map<String, dynamic> json) {
    return DailySerendipityDrop(
      date: DateTime.parse(json['date']),
      llmContextualInsight: json['llmContextualInsight'],
      event: DropEvent.fromJson(json['event']),
      spot: DropSpot.fromJson(json['spot']),
      community: DropCommunity.fromJson(json['community']),
      club: DropClub.fromJson(json['club']),
      wildcard: json['wildcard'] != null
          ? DropWildcard.fromJson(json['wildcard'])
          : null,
      latentCommunity: json['latentCommunity'] != null
          ? DropLatentCommunity.fromJson(json['latentCommunity'])
          : null,
    );
  }
}

abstract class DropItem {
  final String id;
  final String title;
  final String subtitle;
  final String? imageUrl;
  final String? signatureSummary;

  // Why this was chosen based on the user's archetype math
  // e.g. "92% overlap with your primary resonance pattern"
  final double archetypeAffinity;

  DropItem({
    required this.id,
    required this.title,
    required this.subtitle,
    this.imageUrl,
    this.signatureSummary,
    required this.archetypeAffinity,
  });

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'subtitle': subtitle,
      'imageUrl': imageUrl,
      'signatureSummary': signatureSummary,
      'archetypeAffinity': archetypeAffinity,
      'type': runtimeType.toString(),
    };
  }
}

class DropEvent extends DropItem {
  final DateTime time;
  final String locationName;

  DropEvent({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.time,
    required this.locationName,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['time'] = time.toIso8601String();
    map['locationName'] = locationName;
    return map;
  }

  factory DropEvent.fromJson(Map<String, dynamic> json) {
    return DropEvent(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      time: DateTime.parse(json['time']),
      locationName: json['locationName'],
    );
  }
}

class DropSpot extends DropItem {
  final String category; // e.g. "Hidden Cafe"
  final double distanceMiles;

  DropSpot({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.category,
    required this.distanceMiles,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['category'] = category;
    map['distanceMiles'] = distanceMiles;
    return map;
  }

  factory DropSpot.fromJson(Map<String, dynamic> json) {
    return DropSpot(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      category: json['category'],
      distanceMiles: json['distanceMiles'],
    );
  }
}

class DropCommunity extends DropItem {
  final int memberCount;
  final List<String> commonInterests;

  DropCommunity({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.memberCount,
    required this.commonInterests,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['memberCount'] = memberCount;
    map['commonInterests'] = commonInterests;
    return map;
  }

  factory DropCommunity.fromJson(Map<String, dynamic> json) {
    return DropCommunity(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      memberCount: json['memberCount'],
      commonInterests: List<String>.from(json['commonInterests']),
    );
  }
}

class DropClub extends DropItem {
  final String applicationStatus; // e.g. "Open"
  final String vibe;

  DropClub({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.applicationStatus,
    required this.vibe,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['applicationStatus'] = applicationStatus;
    map['vibe'] = vibe;
    return map;
  }

  factory DropClub.fromJson(Map<String, dynamic> json) {
    return DropClub(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      applicationStatus: json['applicationStatus'],
      vibe: json['vibe'],
    );
  }
}

class DropWildcard extends DropItem {
  final String
      doubtReasoning; // e.g. "I know this is weird because you hate mornings, but..."
  final String
      latentVibeMatch; // e.g. "The underground grunge scene here perfectly matches your DNA."

  DropWildcard({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.doubtReasoning,
    required this.latentVibeMatch,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['doubtReasoning'] = doubtReasoning;
    map['latentVibeMatch'] = latentVibeMatch;
    return map;
  }

  factory DropWildcard.fromJson(Map<String, dynamic> json) {
    return DropWildcard(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      doubtReasoning: json['doubtReasoning'],
      latentVibeMatch: json['latentVibeMatch'],
    );
  }
}

class DropLatentCommunity extends DropItem {
  final int discoveredMemberCount;
  final String founderPrompt;

  DropLatentCommunity({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    super.signatureSummary,
    required super.archetypeAffinity,
    required this.discoveredMemberCount,
    required this.founderPrompt,
  });

  @override
  Map<String, dynamic> toJson() {
    final map = super.toJson();
    map['discoveredMemberCount'] = discoveredMemberCount;
    map['founderPrompt'] = founderPrompt;
    return map;
  }

  factory DropLatentCommunity.fromJson(Map<String, dynamic> json) {
    return DropLatentCommunity(
      id: json['id'],
      title: json['title'],
      subtitle: json['subtitle'],
      imageUrl: json['imageUrl'],
      signatureSummary: json['signatureSummary'],
      archetypeAffinity: json['archetypeAffinity'],
      discoveredMemberCount: json['discoveredMemberCount'],
      founderPrompt: json['founderPrompt'],
    );
  }
}
