// import 'package:flutter/material.dart';

/// The core data structure for the Trojan Horse UX (Spike 6).
/// Contains exactly 4 highly curated items derived from the user's 
/// offline physical encounters and learned archetypes.
class DailySerendipityDrop {
  final DateTime date;
  
  // The contextual explanation generated by the local LLM batch process
  // e.g., "Based on the patterns of people you connected with yesterday..."
  final String llmContextualInsight;

  // The 4 hardcoded items
  final DropEvent event;
  final DropSpot spot;
  final DropCommunity community;
  final DropClub club;

  DailySerendipityDrop({
    required this.date,
    required this.llmContextualInsight,
    required this.event,
    required this.spot,
    required this.community,
    required this.club,
  });
}

abstract class DropItem {
  final String id;
  final String title;
  final String subtitle;
  final String? imageUrl;
  
  // Why this was chosen based on the user's archetype math
  // e.g. "92% overlap with your primary resonance pattern"
  final double archetypeAffinity;

  DropItem({
    required this.id,
    required this.title,
    required this.subtitle,
    this.imageUrl,
    required this.archetypeAffinity,
  });
}

class DropEvent extends DropItem {
  final DateTime time;
  final String locationName;

  DropEvent({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    required super.archetypeAffinity,
    required this.time,
    required this.locationName,
  });
}

class DropSpot extends DropItem {
  final String category; // e.g. "Hidden Cafe"
  final double distanceMiles;

  DropSpot({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    required super.archetypeAffinity,
    required this.category,
    required this.distanceMiles,
  });
}

class DropCommunity extends DropItem {
  final int memberCount;
  final List<String> commonInterests;

  DropCommunity({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    required super.archetypeAffinity,
    required this.memberCount,
    required this.commonInterests,
  });
}

class DropClub extends DropItem {
  final String applicationStatus; // e.g. "Open"
  final String vibe;

  DropClub({
    required super.id,
    required super.title,
    required super.subtitle,
    super.imageUrl,
    required super.archetypeAffinity,
    required this.applicationStatus,
    required this.vibe,
  });
}
