#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  scripts/phase_subsection_complete.sh --phase P1 --subsection 1.2.8 [--title "PR title"] [--body "PR body"] [--no-pr] [--skip-naming-verification]

Branch format:
  phase#_work__sX_Y_Z[__sA_B_C...]

What this does:
  1) Requires you to be on phase branch hierarchy.
  2) Creates a child branch from the current branch.
  3) Commits all current changes.
  4) Pushes the child branch.
  5) Runs naming verification unless skipped.
  6) Opens a PR back into the immediate parent branch (unless --no-pr).
USAGE
}

phase=""
subsection=""
pr_title=""
pr_body=""
create_pr="true"
run_naming_verification="true"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --phase)
      phase="${2:-}"
      shift 2
      ;;
    --subsection)
      subsection="${2:-}"
      shift 2
      ;;
    --title)
      pr_title="${2:-}"
      shift 2
      ;;
    --body)
      pr_body="${2:-}"
      shift 2
      ;;
    --no-pr)
      create_pr="false"
      shift
      ;;
    --skip-naming-verification)
      run_naming_verification="false"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "$phase" || -z "$subsection" ]]; then
  echo "Missing required args: --phase and --subsection" >&2
  usage
  exit 1
fi

if git diff --name-only --diff-filter=U | grep -q .; then
  echo "Cannot run with unresolved merge conflicts. Resolve conflicts first." >&2
  exit 1
fi

phase_num="${phase#P}"
phase_num="${phase_num#p}"
if ! [[ "$phase_num" =~ ^[0-9]+$ ]]; then
  echo "Invalid --phase value: $phase (expected P# like P1)" >&2
  exit 1
fi

phase_branch="phase${phase_num}_work"
current_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_pattern="^${phase_branch}(__s[a-z0-9_]+(_r[0-9]+)?)*$"

if ! [[ "$current_branch" =~ $valid_pattern ]]; then
  echo "Current branch is '$current_branch'. Must be '$phase_branch' or child hierarchy under it." >&2
  exit 1
fi

parent_branch="$current_branch"
section_slug="$(echo "$subsection" | tr '.' '_' | tr -cd '[:alnum:]_')"
if [[ -z "$section_slug" ]]; then
  echo "Invalid subsection: $subsection" >&2
  exit 1
fi

child_branch="${parent_branch}__s${section_slug}"
if git show-ref --verify --quiet "refs/heads/${child_branch}"; then
  i=2
  while git show-ref --verify --quiet "refs/heads/${child_branch}_r${i}"; do
    i=$((i + 1))
  done
  child_branch="${child_branch}_r${i}"
fi

echo "Creating child branch: $child_branch"
git switch -c "$child_branch"

git add -A
if git diff --cached --quiet; then
  echo "No changes to commit. Switching back to $parent_branch."
  git switch "$parent_branch"
  git branch -D "$child_branch" >/dev/null 2>&1 || true
  exit 1
fi

commit_msg="${phase^^} ${subsection} complete"
echo "Committing: $commit_msg"
git commit -m "$commit_msg"

echo "Pushing: $child_branch"
git push -u origin "$child_branch"

if [[ "$run_naming_verification" == "true" ]]; then
  echo "Running naming verification gate"
  scripts/verify_phase_naming.sh --phase "$phase" --branch "$child_branch"
fi

if [[ "$create_pr" == "true" ]]; then
  if ! command -v gh >/dev/null 2>&1; then
    echo "gh CLI not found; skipping PR creation." >&2
  else
    if [[ -z "$pr_title" ]]; then
      pr_title="${phase^^} ${subsection} complete"
    fi
    if [[ -z "$pr_body" ]]; then
      pr_body=$(
        cat <<EOF_BODY
Automated subsection completion PR.

- Phase branch root: \`${phase_branch}\`
- Parent branch: \`${parent_branch}\`
- Subsection: \`${subsection}\`
- Source branch: \`${child_branch}\`

Generated by \`scripts/phase_subsection_complete.sh\`.
EOF_BODY
      )
    fi
    echo "Creating PR: $child_branch -> $parent_branch"
    gh pr create \
      --base "$parent_branch" \
      --head "$child_branch" \
      --title "$pr_title" \
      --body "$pr_body"
  fi
fi

echo "Switching back to parent branch: $parent_branch"
git switch "$parent_branch"

echo "Done."
